// Code generated by mockery. DO NOT EDIT.

package templatetest

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockExecuter is an autogenerated mock type for the Executer type
type MockExecuter struct {
	mock.Mock
}

type MockExecuter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecuter) EXPECT() *MockExecuter_Expecter {
	return &MockExecuter_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockExecuter) Execute(_a0 http.ResponseWriter, _a1 *http.Request, _a2 any) {
	_m.Called(_a0, _a1, _a2)
}

// MockExecuter_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockExecuter_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
//   - _a2 any
func (_e *MockExecuter_Expecter) Execute(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockExecuter_Execute_Call {
	return &MockExecuter_Execute_Call{Call: _e.mock.On("Execute", _a0, _a1, _a2)}
}

func (_c *MockExecuter_Execute_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request, _a2 any)) *MockExecuter_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request), args[2].(any))
	})
	return _c
}

func (_c *MockExecuter_Execute_Call) Return() *MockExecuter_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockExecuter_Execute_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request, any)) *MockExecuter_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExecuter creates a new instance of MockExecuter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecuter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecuter {
	mock := &MockExecuter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
