// Code generated by mockery. DO NOT EDIT.

package templatetest

import (
	template "html/template"

	mock "github.com/stretchr/testify/mock"
)

// MockTemplateCloner is an autogenerated mock type for the TemplateCloner type
type MockTemplateCloner struct {
	mock.Mock
}

type MockTemplateCloner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTemplateCloner) EXPECT() *MockTemplateCloner_Expecter {
	return &MockTemplateCloner_Expecter{mock: &_m.Mock}
}

// Clone provides a mock function with given fields:
func (_m *MockTemplateCloner) Clone() (*template.Template, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Clone")
	}

	var r0 *template.Template
	var r1 error
	if rf, ok := ret.Get(0).(func() (*template.Template, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *template.Template); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*template.Template)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTemplateCloner_Clone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clone'
type MockTemplateCloner_Clone_Call struct {
	*mock.Call
}

// Clone is a helper method to define mock.On call
func (_e *MockTemplateCloner_Expecter) Clone() *MockTemplateCloner_Clone_Call {
	return &MockTemplateCloner_Clone_Call{Call: _e.mock.On("Clone")}
}

func (_c *MockTemplateCloner_Clone_Call) Run(run func()) *MockTemplateCloner_Clone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTemplateCloner_Clone_Call) Return(_a0 *template.Template, _a1 error) *MockTemplateCloner_Clone_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTemplateCloner_Clone_Call) RunAndReturn(run func() (*template.Template, error)) *MockTemplateCloner_Clone_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTemplateCloner creates a new instance of MockTemplateCloner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTemplateCloner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTemplateCloner {
	mock := &MockTemplateCloner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
